name = "Havoc Beyond the Clouds"
author = "minecraftbossdj, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c946a91ce1f396ad80ed3d61c5601cf46aa57195a060d55a0ea25d8c29a65c25"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
