name = "Havoc Beyond the Clouds"
author = "minecraftbossdj, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc4195d1998d87d8f9ccaaca9378c579392adef8aac77e1ac638e02a02225e4c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
