name = "Havoc Beyond the Clouds"
author = "minecraftbossdj, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62893100b503888387d25b69e6a85480d67d4a7baab2e4c5d1d231707d80d63f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
