name = "Not So Essential"
filename = "NotSoEssential-Fabric-1.0.8.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/CDo9Niyy/versions/l1JDKmdc/NoChatReports-FORGE-1.20.1-v2.2.2.jar"
hash-format = "sha512"
hash = "c4397cdcc0229e1399367c043fde9e56a75510c2fa845256ec995cc28b4b051cf0bcafe8662a35fea5a5510e9625302a3c103bb62129c29e0e2466d93386faa2"

[update]
[update.modrinth]
mod-id = "CDo9Niyy"
version = "l1JDKmdc"

[option]
optional = true
default = false
description = "Removes essential bloat, NEEDS CONNECTOR. (also not tested with connector)"
